params = {
    "idxAfterPrediction": 5,
    'timesteps': 85,
    'target_option': 'last',
    "LoadupSamples_tree_scaling_standard": True,
    "LoadupSamples_time_scaling_stretch": True,
    "LoadupSamples_time_inc_factor": 36,
    
    "TreeTime_top_n": 5,
    "TreeTime_stoploss": 0.92,
    
    "TreeTime_FilterSamples_method": "taylor",
    "FilterSamples_q_up": 0.65,
    "FilterSamples_days_to_train_end": 10,
    
    "FilterSamples_cat_over20": True,
    "FilterSamples_cat_posOneYearReturn": False,
    "FilterSamples_cat_posFiveYearReturn": False,
    
    "FilterSamples_lincomb_lr": 0.0008,
    "FilterSamples_lincomb_epochs": 150,
    "FilterSamples_lincomb_probs_noise_std": 0.010503627436184224,
    "FilterSamples_lincomb_subsample_ratio": 0.10,
    "FilterSamples_lincomb_sharpness": 0.6,
    "FilterSamples_lincomb_featureratio": 0.33269072850403053,
    "FilterSamples_lincomb_itermax": 3,
    "FilterSamples_lincomb_show_progress": True,
    "FilterSamples_lincomb_init_toprand": 10,

    "FilterSamples_taylor_horizon_days": 60,
    "FilterSamples_taylor_roll_window_days": 15,
    "FilterSamples_taylor_weight_slope": 0.43,

    'TreeTime_run_lstm': True,
    "TreeTime_LSTM_days_to_train": 1000,
    "LSTM_units": 32,
    "LSTM_num_layers": 2,
    "LSTM_dropout": 0.003264,
    "LSTM_recurrent_dropout": 0.028886,
    "LSTM_learning_rate": 0.000135,
    "LSTM_optimizer": "adam",
    "LSTM_bidirectional": True,
    "LSTM_batch_size": 2**12,
    "LSTM_epochs": 4,
    "LSTM_l1": 0.003816,
    "LSTM_l2": 0.000290,
    "LSTM_inter_dropout": 0.001947,
    "LSTM_input_gaussian_noise": 0.0001,
    "LSTM_conv1d": True,
    "LSTM_conv1d_kernel_size": 3,
    "LSTM_loss": "mse",
    
    "TreeTime_LGB_days_to_train":600,
    "LGB_num_boost_round": 400,
    "LGB_lambda_l1": 5e-5,
    "LGB_lambda_l2": 1e-5,
    "LGB_feature_fraction": 0.7,
    "LGB_num_leaves": 300,
    "LGB_max_depth": 7,
    "LGB_learning_rate": 0.019232,
    "LGB_min_data_in_leaf": 400,
    "LGB_min_gain_to_split": 0.13,
    "LGB_path_smooth": 0.6,
    "LGB_min_sum_hessian_in_leaf": 1.0,
    "LGB_max_bin": 500,
    
    "TreeTime_WeightSamples_run": False,
    "WeightSamples_minWeight": 0.4,
    "WeightSamples_truncation": 2,
    "WeightSamples_sparsesamples_ratio": 0.1,
    "WeightSamples_Pricediff": True,
    "WeightSamples_FinData_quar": False,
    "WeightSamples_FinData_metrics": False,
    "WeightSamples_Fourier_RSME": False,
    "WeightSamples_Fourier_Sign": False,
    "WeightSamples_TA_trend": False,
    "WeightSamples_FeatureGroup_VolGrLvl": False,
    "WeightSamples_LSTM_Prediction": False,
}