from abc import ABC, abstractmethod
from typing import List
import datetime
import numpy as np

class IFeature(ABC):
    """Interface for all feature generators."""
    @abstractmethod
    def getFeatureNames(self) -> List[str]:
        """Return list of feature names generated by this class."""
        pass

    @abstractmethod
    def apply(self, trading_days: List[datetime.date]) -> np.ndarray:
        """Compute feature array of shape (n_dates, n_features)."""
        pass